default: &default
  adapter: postgresql
  encoding: unicode
  # 3 connections for Puma, 8 for GoodJob (in async mode, the default for self-hosters) = 16 connections
  pool: <%= ENV.fetch("DB_POOL_SIZE") { 16 } %>
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>
  user: <%= ENV.fetch("POSTGRES_USER") { nil } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { nil } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "maybe_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "maybe_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "maybe_production" } %>
