local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

amazon:
  service: S3
  access_key_id: ENV["S3_ACCESS_KEY_ID"] %>
  secret_access_key: ENV["S3_SECRET_ACCESS_KEY"] %>
  region: us-east-1
  bucket: your_own_bucket-<%= Rails.env %>

# Replace credentials with your own GCS keyfile
google:
  service: GCS
  project: your_project
  credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
  bucket: ENV["GCS_BUCKET"] %>

microsoft:
  service: AzureStorage
  storage_account_name: ENV["AZURE_STORAGE_ACCOUNT_NAME"] %>
  storage_access_key: ENV["AZURE_STORAGE_ACCESS_KEY"] %>
  container: ENV["AZURE_STORAGE_CONTAINER"] %>
